/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface VawPiano {
    /**
    * The last key's note (as midi value)
    */
    'endNote': number;
    /**
    * The first key's note (as midi value)
    */
    'startNote': number;
  }
}

declare namespace LocalJSX {
  interface VawPiano extends JSXBase.HTMLAttributes {
    /**
    * The last key's note (as midi value)
    */
    'endNote'?: number;
    /**
    * The first key's note (as midi value)
    */
    'startNote'?: number;
  }

  interface IntrinsicElements {
    'vaw-piano': VawPiano;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


declare global {



  interface HTMLVawPianoElement extends Components.VawPiano, HTMLStencilElement {}
  var HTMLVawPianoElement: {
    prototype: HTMLVawPianoElement;
    new (): HTMLVawPianoElement;
  };

  interface HTMLElementTagNameMap {
    'vaw-piano': HTMLVawPianoElement;
  }

  interface ElementTagNameMap extends HTMLElementTagNameMap {}
}

